services:
  - type: web
    name: vecinos-virtuales-backend-final
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://bcotgxupjyocbxjdtsaa.supabase.co
      - key: SUPABASE_ANON_KEY
        fromSecret: SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_KEY
        fromSecret: SUPABASE_SERVICE_KEY